apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zveb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-65-tenant/load-app-208677a7-88fc-46d0-ac03-6f849756c49e/devfile-sample-zveb@sha256:f7afcc2a5e835f8a466fd6b0c38bf49243d91bcda7ae5d8f4cd20186dbb23383
        name: my-nodejs
        resources: {}
status: {}
