apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-zveb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-zveb
    app.kubernetes.io/part-of: load-app-208677a7-88fc-46d0-ac03-6f849756c49e
  name: devfile-sample-zveb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-zveb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-zveb
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-65-tenant/load-app-208677a7-88fc-46d0-ac03-6f849756c49e/devfile-sample-zveb@sha256:f7afcc2a5e835f8a466fd6b0c38bf49243d91bcda7ae5d8f4cd20186dbb23383
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
